### ISSUE TITLE
file:// repositories

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/pkgdepends#164] opened 2020-03-22 11:23 UTC
Hello yet again 😊

Does pkgdepends support `file://` URLs as source repositories? It would be nice to be able to install from local repos, eg those created by [miniCRAN](https://github.com/andrie/miniCRAN).

**Comment by gaborcsardi** [comment] 2020-03-22 11:25
Duplicate of #88.

**Closed by gaborcsardi** 2020-03-22 11:25 UTC
