### ISSUE TITLE
Can't install bslib or shiny with dependencies=TRUE

### ISSUE THREAD

**Issue by wch** [r-lib/pkgdepends#232] opened 2021-01-07 17:50 UTC
```
>  pak::pkg_install("rstudio/shiny", dependencies = TRUE, ask=F)
                                                                
→ Will update 2 packages.
→ Will download 2 packages with unknown size.
+ shiny     1.5.0.9006 → 1.5.0.9007 👷🏾‍♀️🔧 ⬇ (GitHub: 5b27d92)
+ shinytest 1.4.0.9002 → 1.4.0.9003 👷🏻🔧 ⬇ (GitHub: 5b566d1)

! shiny is loaded in the current R session, you probably need to restart R
  after the installation.

ℹ Getting 2 pkgs with unknown sizes
✓ Cached copy of shiny 1.5.0.9007 (source) is the latest build
✓ Cached copy of shinytest 1.4.0.9003 (source) is the latest build
✓ No downloads needed, all packages are cached                     
Error: Internal error, no task running and cannot select new task
Type .Last.error.trace to see where the error occured
```

**Comment by gaborcsardi** [comment] 2021-01-07 19:24
Fixed by c3ea8c52ebb0bed5b6bcd1b3f422a47cd451d36a

**Closed by gaborcsardi** 2021-01-07 19:24 UTC

**Comment by gaborcsardi** [comment] 2021-01-07 19:25
@wch these binaries should be better: https://github.com/r-lib/pak/actions?query=workflow%3A%22Build+pak+binary%22

**Comment by gaborcsardi** [comment] 2021-01-07 19:40
Well, it was about circular dependencies, after all, because circular dependencies triggered it. :)

**Comment by schloerke** [comment] 2021-01-07 20:28
Confirmed it works on my end. Thank you!
